alias g='grep -i'
alias grep='grep --color=always'
alias ls='ls -CF --color=always'
alias ll='ls -l --color=always'
alias la='ls -A --color=always'
alias up='cd ..'
alias codes='cd ~/Documents/Codes/'
alias emacs='emacsclient -nw'
alias tmux='TERM=xterm-24bit tmux'
alias yr='tmuxp load ~/.config/tmuxp/yreceipts.yaml'
alias yr-nw='tmuxp load ~/.config/tmuxp/yreceipts-nw.yaml'
