alias grep='grep --color=always'
alias ls='ls -CF --color=always'
alias cls='clear; ls'
alias emacs='emacsclient -nw'
alias tmux='TERM=xterm-24bit tmux'
alias yr='tmuxp load ~/.config/tmuxp/yreceipts.yaml'
alias yr-nw='tmuxp load ~/.config/tmuxp/yreceipts-nw.yaml'
